version: '3.8'

services:
  issuer:
    build:
      context: .
      dockerfile: issuer/Dockerfile
    container_name: did-issuer
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - SERVICE_ENDPOINT=http://did-issuer:5001/didcomm
    networks:
      - did-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  holder:
    build:
      context: .
      dockerfile: holder/Dockerfile
    container_name: did-holder
    ports:
      - "5003:5003"
    environment:
      - NODE_ENV=production
      - PORT=5003
      - SERVICE_ENDPOINT=http://did-holder:5003/didcomm
      - DB_PATH=/data/holder-credentials.db
    volumes:
      - holder-data:/data
    networks:
      - did-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  verifier:
    build:
      context: .
      dockerfile: verifier/Dockerfile
    container_name: did-verifier
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
      - PORT=5002
      - SERVICE_ENDPOINT=http://did-verifier:5002/didcomm
    networks:
      - did-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  holder-wallet:
    build:
      context: ./demo/holder-wallet
      dockerfile: Dockerfile
    container_name: did-holder-wallet
    ports:
      - "5173:80"
    networks:
      - did-network
    restart: unless-stopped
    depends_on:
      - holder
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  issuer-web:
    build:
      context: ./demo/issuer-web
      dockerfile: Dockerfile
    container_name: did-issuer-web
    ports:
      - "5171:80"
    networks:
      - did-network
    restart: unless-stopped
    depends_on:
      - issuer
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  verifier-web:
    build:
      context: ./demo/verifier-web
      dockerfile: Dockerfile
    container_name: did-verifier-web
    ports:
      - "5172:80"
    networks:
      - did-network
    restart: unless-stopped
    depends_on:
      - verifier
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  did-network:
    driver: bridge

volumes:
  holder-data:
    driver: local

